/**:
  ros__parameters:
    update_rate: 10.0
    add_duplicated_node_names_to_msg: true # if true, duplicated node names are added to msg
    nodes_to_ignore:  # List of nodes to ignore when checking for duplicates
      - /rviz2
