/**:
  ros__parameters:
    interval_sec: 1.0  # [sec]
    threshold_diff_position_x: 0.1  # [m]
    threshold_diff_position_y: 0.1  # [m]
    threshold_diff_position_z: 0.1  # [m]
    threshold_diff_angle_x: 0.1  # [rad]
    threshold_diff_angle_y: 0.1  # [rad]
    threshold_diff_angle_z: 0.1  # [rad]
