/**:
  ros__parameters:
    lane_change:
      lane_change_prepare_duration: 4.0
      lane_changing_duration: 8.0
      lane_change_finish_judge_buffer: 3.0
      minimum_lane_change_velocity: 5.6
      prediction_time_resolution: 0.5
      maximum_deceleration: 1.0
      lane_change_sampling_num: 10
      enable_abort_lane_change: false
      enable_collision_check_at_prepare_phase: false
      use_predicted_path_outside_lanelet: false
      use_all_predicted_path: false
      lane_change_search_distance: 30.0
