# This file is automatically synced from:
# https://github.com/autowarefoundation/sync-file-templates
# To make changes, update the source repository and follow the guidelines in its README.

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduleinterval
    schedule:
      interval: monthly
    open-pull-requests-limit: 1
    labels:
      - tag:bot
      - type:github-actions
