# This file is automatically synced from:
# https://github.com/autowarefoundation/sync-file-templates
# To make changes, update the source repository and follow the guidelines in its README.

# Modified from https://github.com/probot/stale#usage

# Number of days of inactivity before an Issue or Pull Request with the stale label is closed
daysUntilClose: false

# Label to use when marking as stale
staleLabel: status:stale

# Comment to post when marking as stale
markComment: >
  This pull request has been automatically marked as stale because it has not had
  recent activity.
