/**:
  ros__parameters:
    hdd_reader_port: 7635
    num_disks: 1
    disks: # Until multi type lists are allowed, name N the disks as disk0...disk{N-1}
      disk0:
        name: /
        temp_attribute_id: 0xC2
        temp_warn: 55.0
        temp_error: 70.0
        power_on_hours_attribute_id: 0x09
        power_on_hours_warn: 3000000
        total_data_written_attribute_id: 0xF1
        total_data_written_warn: 4915200   # =150TB (1unit=32MB)
        total_data_written_safety_factor: 0.05
        recovered_error_attribute_id: 0xC3
        recovered_error_warn: 1
        free_warn: 5120 # MB(8hour)
        free_error: 100 # MB(last 1 minute)
        read_data_rate_warn: 360.0 # MB/s
        write_data_rate_warn: 103.5 # MB/s
        read_iops_warn: 63360.0 # IOPS
        write_iops_warn: 24120.0 # IOPS
