# This is required for Continuous Integration for Autoware using the simulator
# and remote update (Over The Air update) to real cars.
# If you have any additional questions, please contact us at #tier4-dev channel.

version: 2

artifacts:
  - name: main
    build:
      type: tier4/iv/main/amd64/v2

simulations:
  - name: planning_sim_v2
    type: planning_sim_v2
    simulator:
      deployment:
        type: container
        artifact: main
      runtime:
        type: simulator/standard1/amd64/medium
        cpu: 8
        memory: 16384
      parameters:
        vehicle_model: lexus
        sensor_model: aip_xx1
        autoware_launch_package: autoware_launch
        autoware_launch_file: planning_simulator.launch.xml
        architecture_type: awf/universe
        initialize_duration: "90"

  - name: log_sim_v2
    type: log_sim_v2
    simulator:
      deployment:
        type: container
        artifact: main
      runtime:
        type: simulator/standard1/amd64/medium
        cpu: 8
        memory: 16384
