#include "autoware_auto_mapping_msgs/msg/HADMapSegment.idl"
#include "geometry_msgs/msg/Pose.idl"
#include "std_msgs/msg/Header.idl"

module autoware_auto_planning_msgs {
  module msg {
    @verbatim (language="comment", text=
      " A route within a high-definition map defined by"
      " the start and goal points and map primitives"
      " describing the route between the two.")
    struct HADMapRoute {
      std_msgs::msg::Header header;

      @verbatim (language="comment", text=
        " The start_pose must exist within the bounds of the primitives in the first"
        " segment defined in the route_segments array.")
      geometry_msgs::msg::Pose start_pose;

      @verbatim (language="comment", text=
        " The goal_pose must exist within the bounds of the primitives in the last"
        " segment defined in the route_semgents array.")
      geometry_msgs::msg::Pose goal_pose;

      sequence<autoware_auto_mapping_msgs::msg::HADMapSegment> segments;
    };
  };
};
