#include "geometry_msgs/msg/Pose.idl"
#include "geometry_msgs/msg/Twist.idl"

module autoware_auto_planning_msgs {
  module msg {
    @verbatim (language = "comment", text=
      "Represents a pose from a lanelet map, contains twist information.")
    struct PathPoint {
      geometry_msgs::msg::Pose pose;

      @default (value=0.0)
      float longitudinal_velocity_mps;

      @default (value=0.0)
      float lateral_velocity_mps;

      @default (value=0.0)
      float heading_rate_rps;

      @verbatim(language = "comment", text =
        "Denotes that the point is final, doesn't need further updates.")
      @default (value = FALSE)
      boolean is_final;
    };
  };
};
