/**:
  ros__parameters:
    prediction_path: "/home/kaan/projects/autoware/src/universe/autoware/benchmarking/perception_benchmark_tool/benchmarking_result/predictions_6.bin"
    ground_truth_path: "/home/kaan/projects/autoware/src/universe/autoware/benchmarking/perception_benchmark_tool/benchmarking_result/gt_6.bin"
