/**:
  ros__parameters:
    error_thresholds:
      # Threshold value for the range in which GNSS position error is most reliable
      gnss_error_reliable_max: 0.1      #meters

      # Threshold value at which GNSS position error is not considered reliable
      gnss_error_unreliable_min: 0.25   #meters

      # Threshold value for yaw error
      yaw_error_deg_threshold: 0.3      #degrees

    # Acceptable delay duration for GNSS pose data [sec]
    gnss_pose_timeout_sec: 1.0  #seconds

    debug:
      enable_debug_topics: true
