units:
  - path: /autoware/localization
    type: short-circuit-and
    list:
      - type: link
        link: /autoware/localization/state
      - type: and
        list:
          - { type: link, link: /autoware/localization/topic_rate_check/transform }
          - { type: link, link: /autoware/localization/topic_rate_check/pose_twist_fusion }
          - { type: link, link: /autoware/localization/scan_matching_status }
          - { type: link, link: /autoware/localization/accuracy }
          - { type: link, link: /autoware/localization/sensor_fusion_status }

  - path: /autoware/localization/state
    type: diag
    node: component_state_diagnostics
    name: localization_state

  - path: /autoware/localization/topic_rate_check/transform
    type: diag
    node: topic_state_monitor_transform_map_to_base_link
    name: localization_topic_status

  - path: /autoware/localization/topic_rate_check/pose_twist_fusion
    type: diag
    node: topic_state_monitor_pose_twist_fusion_filter_pose
    name: localization_topic_status

  - path: /autoware/localization/scan_matching_status
    type: diag
    node: ndt_scan_matcher
    name: scan_matching_status

  - path: /autoware/localization/accuracy
    type: diag
    node: localization_error_monitor
    name: ellipse_error_status

  - path: /autoware/localization/sensor_fusion_status
    type: diag
    node: localization
    name: ekf_localizer
