nodes:
  - path: /autoware/map
    type: and
    list:
      - type: diag
        name: "topic_state_monitor_vector_map: map_topic_status"
        hardware: topic_state_monitor
      - type: diag
        mode: [psim!]
        name: "topic_state_monitor_pointcloud_map: map_topic_status"
        hardware: topic_state_monitor
