nodes:
  - name: /autoware/planning
    type: and
    list:
      - type: diag
        name: "component_state_diagnostics: route_state"
      - type: diag
        name: "topic_state_monitor_mission_planning_route: planning_topic_status"
        hardware: topic_state_monitor
      - type: diag,
        name: "topic_state_monitor_scenario_planning_trajectory: planning_topic_status"
        hawdware: topic_state_monitor
