/**:
  ros__parameters:
    binary_bayes_filter2:
      probability_matrix:
        occupied_to_occupied: 0.95
        occupied_to_free: 0.05
        free_to_occupied: 0.2
        free_to_free: 0.8
      decay_rate: 5.0
