#include "builtin_interfaces/msg/Time.idl"

module communication_delay_compensator{
  module msg {
    @verbatim (language = "comment", text = "Delay Compensation Debug Message")
    struct DelayCompensationDebug
    {
      builtin_interfaces::msg::Time stamp;

      // Lateral Error
      @verbatim (language = "comment", text = "filtered output for the lateral error input")
      @default (value = 0.0)
      double lat_uf;

      @verbatim (language = "comment", text = "filtered output for the lateral error disturbance estimate")
      @default (value = 0.0)
      double lat_duf;

      @verbatim (language = "comment", text = "state observer output, lateral error estimate")
      @default (value = 0.0)
      double lat_ey_hat;

      @verbatim (language = "comment", text = "state observer output, yaw error estimate")
      @default (value = 0.0)
      double lat_eyaw_hat;

      @verbatim (language = "comment", text = "state observer output, steering state estimate")
      @default (value = 0.0)
      double lat_steering_hat;

      @verbatim (language = "comment", text = "time delay compensator ey compensation reference")
      @default (value = 0.0)
      double td_ey_ref;

      @verbatim (language = "comment", text = "time delay compensator eyaw compensation reference")
      @default (value = 0.0)
      double td_eyaw_ref;

      @verbatim (language = "comment", text = "time delay compensator steering compensation reference")
      @default (value = 0.0)
      double td_steering_ref;

    };
  };
};

