/**:
  ros__parameters:

    # Latitude of local origin
    latitude: 41.114054023192345

    # Longitude of local origin
    longitude: 29.010876695434675

    # Altitude of local origin
    altitude: 18.700321762959675
