#include "autoware_auto_perception_msgs/msg/PredictedPath.idl"
#include "geometry_msgs/msg/AccelWithCovariance.idl"
#include "geometry_msgs/msg/PoseWithCovariance.idl"
#include "geometry_msgs/msg/TwistWithCovariance.idl"

module autoware_auto_perception_msgs {
  module msg {
    struct PredictedObjectKinematics {
      geometry_msgs::msg::PoseWithCovariance initial_pose_with_covariance;

      geometry_msgs::msg::TwistWithCovariance initial_twist_with_covariance;

      geometry_msgs::msg::AccelWithCovariance initial_acceleration_with_covariance;

      sequence<autoware_auto_perception_msgs::msg::PredictedPath, 100> predicted_paths;
    };
  };
};
