#include "autoware_auto_perception_msgs/msg/TrackedObject.idl"
#include "std_msgs/msg/Header.idl"

module autoware_auto_perception_msgs {
  module msg {
    @verbatim (language="comment", text=
      " This is the output of object tracking and the input to prediction.")
    struct TrackedObjects {
      std_msgs::msg::Header header;
      sequence<autoware_auto_perception_msgs::msg::TrackedObject> objects;
    };
  };
};
