#include "autoware_auto_perception_msgs/msg/TrafficSignal.idl"
#include "std_msgs/msg/Header.idl"

module autoware_auto_perception_msgs {
  module msg {
    struct TrafficSignalArray {
      std_msgs::msg::Header header;
      sequence<autoware_auto_perception_msgs::msg::TrafficSignal> signals;
    };
  };
};
