# This file is automatically synced from:
# https://github.com/autowarefoundation/sync-file-templates
# To make changes, update the source repository and follow the guidelines in its README.

blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/autowarefoundation/autoware/discussions/new?category=q-a
    about: Ask a question

  - name: Feature request
    url: https://github.com/autowarefoundation/autoware/discussions/new?category=feature-requests
    about: Send a feature request

  - name: Idea
    url: https://github.com/autowarefoundation/autoware/discussions/new?category=ideas
    about: Post an idea
