#include "sensor_msgs/msg/PointCloud2.idl"

module autoware_auto_msgs {
  module msg {
    @verbatim (language="comment", text=
      " This is a temporary message type until DDS keys are made available in the standard header" "\n"
      " TODO(c.ho) deprecate when DDS keys are made available" "\n"
      " Check for when https://index.ros.org/doc/ros2/Tutorials/Rosidl-Tutorial/ updates")
    struct PointClusters {
      sequence<sensor_msgs::msg::PointCloud2> clusters;
    };
  };
};
