#include "geometry_msgs/msg/Polygon.idl"

module autoware_auto_msgs {
  module msg {
    struct Shape {
      @verbatim (language="comment", text=
        " A 2D polygon describing the outline of an object. All z components should"
        " be set to the minimum height of the object.")
      geometry_msgs::msg::Polygon polygon;

      @verbatim (language="comment", text=
        " The overall height of the object in meters.")
      float height;
    };
  };
};
