#include "geometry_msgs/msg/AccelWithCovariance.idl"
#include "geometry_msgs/msg/PoseWithCovariance.idl"
#include "geometry_msgs/msg/TwistWithCovariance.idl"

module autoware_auto_msgs {
  module msg {
    struct TrackedObjectKinematics {
      geometry_msgs::msg::PoseWithCovariance pose;

      geometry_msgs::msg::TwistWithCovariance twist;

      geometry_msgs::msg::AccelWithCovariance acceleration;

      @value (default=False)
      boolean is_stationary;
    };
  };
};
