#include "autoware_auto_msgs/msg/ObjectClassification.idl"
#include "autoware_auto_msgs/msg/Shape.idl"
#include "autoware_auto_msgs/msg/TrackedObjectKinematics.idl"

module autoware_auto_msgs {
  module msg {
    struct TrackedObject {
      uint64 object_id;

      @range (min=0.0, max=1.0)
      float existence_probability;

      sequence<autoware_auto_msgs::msg::ObjectClassification> classification;
      autoware_auto_msgs::msg::TrackedObjectKinematics kinematics;

      @verbatim (language="comment", text=
        "If an object is not articulated, only index 0 is populated.")
      sequence<autoware_auto_msgs::msg::Shape, 5> shape;
    };
  };
};
