#include "builtin_interfaces/msg/Time.idl"

module autoware_auto_msgs {
  module msg {
    module TurnIndicatorsReport_Constants {
      const uint8 DISABLE = 0;
      const uint8 ENABLE_LEFT = 1;
      const uint8 ENABLE_RIGHT = 2;
    };

    struct TurnIndicatorsReport {
      builtin_interfaces::msg::Time stamp;

      @default (value=0)
      uint8 report;
    };
  };
};

