/**:
  ros__parameters:
    lanelet2_map_projector_type: MGRS

    # Latitude of map_origin, using in UTM
    latitude: 40.816617984672746

    # Longitude of map_origin, using in UTM
    longitude: 29.360491808334285

    center_line_resolution: 5.0
