/**:
  ros__parameters:
    allow_unsupported_version: true             # flag to load unsupported format_version anyway. If true, just prints warning.
    use_waypoints: true                         # "centerline" in the Lanelet2 map will be used as a "waypoints" tag.
    lanelet2_map_path: $(var lanelet2_map_path) # The lanelet2 map path
