/**:
  ros__parameters:
    common:
      enable_debug_info: false
      enable_calculation_time_info: false

      nearest_dist_deviation_threshold: 3.0 # [m] for finding nearest index
      nearest_yaw_deviation_threshold: 1.57 # [rad] for finding nearest index

    behavior_determination:
      pointcloud_search_radius: 5.0
      pointcloud_voxel_grid_x: 0.05
      pointcloud_voxel_grid_y: 0.05
      pointcloud_voxel_grid_z: 100000.0
      pointcloud_cluster_tolerance: 1.0
      pointcloud_min_cluster_size: 1
      pointcloud_max_cluster_size: 100000

      decimate_trajectory_step_length : 2.0 # longitudinal step length to calculate trajectory polygon for collision checking

      prediction_resampling_time_interval: 0.1
      prediction_resampling_time_horizon: 10.0

      # if crossing vehicle is determined as target obstacles or not
      crossing_obstacle:
        obstacle_velocity_threshold : 3.0 # velocity threshold for crossing obstacle for cruise or stop [m/s]
        obstacle_traj_angle_threshold : 1.22 # [rad] = 70 [deg], yaw threshold of crossing obstacle against the nearest trajectory point for cruise or stop

      # consider the current ego pose (it is not the nearest pose on the reference trajectory)
      # Both the lateral error and the yaw error are assumed to decrease to zero by the time duration "time_to_convergence"
      # The both errors decrease with constant rates against the time.
      consider_current_pose:
        enable_to_consider_current_pose: true
        time_to_convergence: 1.5 #[s]
