/**:
  ros__parameters:
    fallback_trajectory_timeout: 0.5  # [s] age below which a fallback trajectory can be used
    preprocessing:
      force_zero_initial_deviation: True  # if true, initial planning starts from the reference path
      force_zero_initial_heading: True # if true, initial planning starts with a heading aligned with the reference path
      smooth_reference_trajectory:
        enable: True # if true, the reference trajectory is smoothed before being used for planning
        control_points_ratio: 0.3
        smoothing_weight: 0.001
    postprocessing:
      desired_traj_behind_length: 5.0 # [m] desired trajectory length behind the current ego position
    constraints:
      hard:
        max_curvature: 0.2  # [1/m]
        min_curvature: -0.2  # [1/m]
        max_acceleration: 2.0  # [m/s²]
        min_acceleration: -2.0  # [m/s²]
        max_velocity: 3.0  # [m/s]
        min_velocity: -0.5  # [m/s]
      soft:
        lateral_deviation_weight: 0.1
        longitudinal_deviation_weight: 1.0
        jerk_weight: 1.0
        length_weight: -1.0  # negative weight to turn the length cost into a reward
        curvature_weight: 1.0
        velocity_weight: -1.0
    sampling:
      enable_frenet: True
      enable_bezier: True
      resolution: 0.2
      minimum_committed_length: 10.0
      reuse_max_length_max: 20.0
      reuse_samples: 4
      reuse_max_deviation: 1.0
      target_lengths: [20.0, 40.0, 60.0]
      frenet:
        manual: true # true will use the bellow values; false will calculate the values from the problem inputs
        target_durations: [5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0]
        target_longitudinal_position_offsets: [15.0, 20.0, 25.0, 30.0, 35.0, 40.0]  # added to the current ego position
        target_longitudinal_velocities: [0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0]
        target_longitudinal_accelerations: [0.0]
        target_lateral_positions: [-0.5, -0.25, 0.0, 0.25, 0.5]
        target_lateral_velocities: [0.0]
        target_lateral_accelerations: [0.0]
      bezier:
        nb_k: 3
        mk_min: 0.0
        mk_max: 10.0
        nb_t: 10
        mt_min: 0.3
        mt_max: 1.7
