/**:
  ros__parameters:
    fallback_trajectory_timeout: 0.5  # [s] age below which a fallback trajectory can be used
    preprocessing:
      force_zero_initial_deviation: False # if true, initial planning starts from the reference path
      force_zero_initial_heading: False # if true, initial planning starts with a heading aligned with the reference path
      smooth_reference_trajectory:
        enable: False # if true, the reference trajectory is smoothed before being used for planning
        control_points_ratio: 0.3
        smoothing_weight: 0.001
    postprocessing:
      desired_traj_behind_length: 5.0 # [m] desired trajectory length behind the current ego position
    constraints:
      hard:
        max_curvature: 0.2  # [1/m]
        min_curvature: -0.2  # [1/m]
        max_acceleration: 2.0  # [m/s²]
        min_acceleration: -2.0  # [m/s²]
        max_velocity: 3.0  # [m/s]
        min_velocity: -0.5  # [m/s]
        collision_distance_buffer: 1.0 # [m]
      soft:
        lateral_deviation_weight: 0.1
        longitudinal_deviation_weight: 1.0
        jerk_weight: 1.0
        length_weight: 1.0
        curvature_weight: 1.0
        velocity_weight: -1.0
    sampling:
      enable_frenet: True
      enable_bezier: True
      resolution: 0.2
      minimum_committed_length: 5.0
      reuse_max_length_max: 25.0
      reuse_samples: 5
      reuse_max_deviation: 1.5
      target_lengths: [20.0, 40.0, 60.0]
      frenet:
        manual:  # use combinations of the values defined below as target states to generate candidate trajectories
          enable: False
          target_durations: [5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0]
          target_longitudinal_position_offsets: [15.0, 20.0, 25.0, 30.0, 35.0, 40.0]  # added to the current ego position
          target_longitudinal_velocities: [0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0]
          target_longitudinal_accelerations: [0.0]
          target_lateral_positions: [-2.0, -1.5, -1.0, -0.5, 0.0, 0.5, 1.0, 1.5, 2.0]
          target_lateral_velocities: [0.0]
          target_lateral_accelerations: [0.0]
        calc:  # automatically calculate target states from the problem inputs
          enable: True
          target_longitudinal_velocity_samples: 10
      bezier:
        nb_k: 3
        mk_min: 0.0
        mk_max: 10.0
        nb_t: 10
        mt_min: 0.3
        mt_max: 1.7
