/**:
  ros__parameters:
    lateral_controller_mode: "mpc"
    longitudinal_controller_mode: "pid"

    # steer offset
    steering_offset:
      enable_auto_steering_offset_removal: true
      update_vel_threshold: 5.56
      update_steer_threshold: 0.035
      average_num: 1000
      steering_offset_limit: 0.02
