/default_ad_api/node/autoware_state:
  ros__parameters:
    update_rate: 10.0

/default_ad_api/node/motion:
  ros__parameters:
    require_accept_start: false
    stop_check_duration: 1.0

/default_ad_api/node/planning:
  ros__parameters:
    stop_distance: 1.0
    stop_duration: 1.0