/**:
  ros__parameters:
    time_safety_buffer: 1.5  # [s] required time without collision in forward simulation
    dist_safety_buffer: 1.5  # [m] distance from obstacles to consider a collision
    downsample_factor: 10  # factor by which to downsample the input trajectory for calculation
