#include "builtin_interfaces/msg/Time.idl"

module autoware_auto_vehicle_msgs {
  module msg {
    module ControlModeCommand_Constants {
      const uint8 NO_COMMAND = 0;
      const uint8 AUTONOMOUS = 1;
      const uint8 MANUAL = 2;
    };
    @verbatim (language="comment", text=
      " ControlModeCommand.msg")
    struct ControlModeCommand {
      builtin_interfaces::msg::Time stamp;

      @default (value=0)
      uint8 mode;
    };
  };
};
