#include "builtin_interfaces/msg/Time.idl"

module autoware_auto_vehicle_msgs {
  module msg {
    @verbatim (language="comment", text=
    " Command for controlling an electronic hand brake.")

    struct HandBrakeCommand {
      builtin_interfaces::msg::Time stamp;

      @default (value=FALSE)
      boolean active;
    };
  };
};

