#include "builtin_interfaces/msg/Time.idl"

module autoware_auto_vehicle_msgs {
  module msg {
    @verbatim (language="comment", text=
      " VelocityReport.msg")
    struct VelocityReport {
      builtin_interfaces::msg::Time stamp;

      @default (value=0.0)
      float longitudinal_velocity;

      @default (value=0.0)
      float lateral_velocity;

      @default (value=0.0)
      float heading_rate;
    };
  };
};
