/**:
  ros__parameters:
    goal_planner:
      # general params
      th_arrived_distance: 1.0
      th_stopped_velocity: 0.01
      th_stopped_time: 2.0  # It must be greater than the state_machine's.
      center_line_path_interval: 1.0

      # goal search
      goal_search:
        goal_priority: "minimum_weighted_distance" # "minimum_weighted_distance" or "minimum_longitudinal_distance"
        minimum_weighted_distance:
          lateral_weight: 40.0
        prioritize_goals_before_objects: true
        parking_policy: "left_side" # "left_side" or "right_side"
        forward_goal_search_length: 40.0
        backward_goal_search_length: 20.0
        goal_search_interval: 2.0
        longitudinal_margin: 3.0
        max_lateral_offset: 1.0
        lateral_offset_interval: 0.5
        ignore_distance_from_lane_start: 0.0
        margin_from_boundary: 0.75
        high_curvature_threshold: 0.1
        bus_stop_area:
          use_bus_stop_area: false
          goal_search_interval: 0.75
          lateral_offset_interval: 0.3

      # occupancy grid map
      occupancy_grid:
        use_occupancy_grid_for_goal_search: true
        use_occupancy_grid_for_goal_longitudinal_margin: false
        use_occupancy_grid_for_path_collision_check: false
        occupancy_grid_collision_check_margin: 0.0
        theta_size: 360
        obstacle_threshold: 60

      # object recognition
      object_recognition:
        collision_check_soft_margins: [5.0, 4.5, 4.0, 3.5, 3.0, 2.5, 2.0, 1.5, 1.0]  # the maximum margin when ego and objects are oriented.
        collision_check_hard_margins: [0.6]  # this should be larger than `surround_check_distance` of surround_obstacle_checker
        object_recognition_collision_check_max_extra_stopping_margin: 1.0
        th_moving_object_velocity: 1.0
        detection_bound_offset: 15.0
        outer_road_detection_offset: 1.0
        inner_road_detection_offset: 0.0


      # pull over
      pull_over:
        minimum_request_length: 0.0
        pull_over_prepare_length: 100.0
        pull_over_velocity: 3.0
        pull_over_minimum_velocity: 1.38
        decide_path_distance: 10.0
        maximum_deceleration: 1.0
        maximum_jerk: 1.0
        path_priority: "efficient_path" # "efficient_path" or "close_goal"
        efficient_path_order: ["SHIFT", "ARC_FORWARD", "ARC_BACKWARD"] # only lane based pull over(exclude freespace parking)
        lane_departure_check_expansion_margin: 0.2

        # shift parking
        shift_parking:
          enable_shift_parking: true
          shift_sampling_num: 4
          maximum_lateral_jerk: 2.0
          minimum_lateral_jerk: 0.5
          deceleration_interval: 15.0
          after_shift_straight_distance: 1.0

        # parallel parking path
        parallel_parking:
          path_interval: 1.0
          max_steer_angle: 0.4 #22.9deg
          forward:
            enable_arc_forward_parking: true
            after_forward_parking_straight_distance: 2.0
            forward_parking_velocity: 1.38
            forward_parking_lane_departure_margin: 0.0
            forward_parking_path_interval: 1.0
            forward_parking_max_steer_angle: 0.4  # 22.9deg
          backward:
            enable_arc_backward_parking: true
            after_backward_parking_straight_distance: 2.0
            backward_parking_velocity: -1.38
            backward_parking_lane_departure_margin: 0.0
            backward_parking_path_interval: 1.0
            backward_parking_max_steer_angle: 0.4  # 22.9deg

        # freespace parking
        freespace_parking:
          enable_freespace_parking: true
          freespace_parking_algorithm: "astar"  # options: astar, rrtstar
          velocity: 1.0
          vehicle_shape_margin: 1.0
          time_limit: 3000.0
          max_turning_ratio: 0.5
          turning_steps: 1
          # search configs
          search_configs:
            theta_size: 120
            angle_goal_range: 6.0
            lateral_goal_range: 0.5
            longitudinal_goal_range: 2.0
            curve_weight: 0.5
            reverse_weight: 1.0
            direction_change_weight: 1.5
          # costmap configs
          costmap_configs:
            obstacle_threshold: 30
          # -- A* search Configurations --
          astar:
            search_method: "forward"  # options: forward, backward
            only_behind_solutions: false
            use_back: true
            adapt_expansion_distance: true
            expansion_distance: 0.5
            near_goal_distance: 3.0
            distance_heuristic_weight: 2.0
            smoothness_weight: 0.5
            obstacle_distance_weight: 1.75
            goal_lat_distance_weight: 5.0
          # -- RRT* search Configurations --
          rrtstar:
            enable_update: true
            use_informed_sampling: true
            max_planning_time: 150.0
            neighbor_radius: 8.0
            margin: 1.0

        bezier_parking:
          pull_over_angle_threshold: 0.5
          after_shift_straight_distance: 1.5

      stop_condition:
        maximum_deceleration_for_stop: 1.0
        maximum_jerk_for_stop: 1.0
      path_safety_check:
        # EgoPredictedPath
        ego_predicted_path:
          min_velocity: 1.0
          min_acceleration: 1.0
          max_velocity: 1.0
          time_horizon_for_front_object: 5.0
          time_horizon_for_rear_object: 5.0
          time_resolution: 0.5
          delay_until_departure: 1.0
        # For target object filtering
        target_filtering:
          safety_check_time_horizon: 5.0
          safety_check_time_resolution: 1.0
          # detection range
          object_check_forward_distance: 100.0
          object_check_backward_distance: 100.0
          ignore_object_velocity_threshold: 1.0
          # ObjectTypesToCheck
          object_types_to_check:
            check_car: true
            check_truck: true
            check_bus: true
            check_trailer: true
            check_bicycle: true
            check_motorcycle: true
            check_pedestrian: true
            check_unknown: false
          # ObjectLaneConfiguration
          object_lane_configuration:
            check_current_lane: true
            check_right_side_lane: true
            check_left_side_lane: true
            check_shoulder_lane: true
            check_other_lane: false
          include_opposite_lane: false
          invert_opposite_lane: false
          check_all_predicted_path: true
          use_all_predicted_path: true
          use_predicted_path_outside_lanelet: false

        # For safety check
        safety_check_params:
          # safety check configuration
          enable_safety_check: true
          method: "integral_predicted_polygon"
          keep_unsafe_time: 0.5
          # collision check parameters
          publish_debug_marker: false
          rss_params:
            rear_vehicle_reaction_time: 2.0
            rear_vehicle_safety_time_margin: 1.0
            lateral_distance_max_threshold: 2.0
            longitudinal_distance_min_threshold: 3.0
            longitudinal_velocity_delta_time: 0.8
          integral_predicted_polygon_params:
            forward_margin: 1.0
            backward_margin: 1.0
            lat_margin: 1.0
            time_horizon: 5.0
          # hysteresis factor to expand/shrink polygon with the value
          hysteresis_factor_expand_rate: 1.0
          collision_check_yaw_diff_threshold: 3.1416
          # temporary
          backward_path_length: 30.0
          forward_path_length: 100.0

      # debug
      debug:
        print_debug_info: false
