/**:
  ros__parameters:
    freespace_planning_algoriths:
      astar.only_behind_solutions: false
      astar.use_back: true
      astar.distance_heuristic_weight: 1.0
      rrtstar.enable_update: true
      rrtstar.use_informed_sampling: true
      rrtstar.mac_planning_time: 150.0
      rrtstar.neighbor_radius: 8.0
      rrtstar.margin: 0.1
