/**:
  ros__parameters:

    max_iteration: 500

    sample_count: 4

    inlier_ratio: 0.2

    error_threshold: 0.996 # = cos(5[deg])

    lsd_sigma: 1.5

    opt:
      max_vertex_cnt: 10
      imu_factor_gain: 1.0
      vp_factor_gain: 2.0
      hz_factor_gain: 2.0
      verbose: false