/**:
  ros__parameters:
    input_offset_ms: [61.67, 111.67, 45.0, 28.33, 78.33, 95.0]
    timeout_ms: 70.0
    match_threshold_ms: 50.0
    image_buffer_size: 15
    debug_mode: false
    filter_scope_minx: -100.0
    filter_scope_miny: -100.0
    filter_scope_minz: -100.0
    filter_scope_maxx: 100.0
    filter_scope_maxy: 100.0
    filter_scope_maxz: 100.0
