/**:
  ros__parameters:
    # if the semantic label is applied for pointcloud filtering

    filter_semantic_label_target:
      UNKNOWN: false
      BUILDING: true
      WALL: true
      OBSTACLE: false
      TRAFFIC_LIGHT: false
      TRAFFIC_SIGN: false
      PERSON: false
      VEHICLE: false
      BIKE: false
      ROAD: true
      SIDEWALK: false
      ROADPAINT: false
      CURBSTONE: false
      CROSSWALK: false
      VEGETATION: true
      SKY: false

    # the maximum distance of pointcloud to be applied filter
    filter_distance_threshold: 60.0

    # debug
    debug_mode: false
    filter_scope_min_x: -100.0
    filter_scope_max_x: 100.0
    filter_scope_min_y: -100.0
    filter_scope_max_y: 100.0
    filter_scope_min_z: -100.0
    filter_scope_max_z: 100.0
