/**:
  ros__parameters:
    # if the semantic label is applied for pointcloud filtering
    filter_semantic_label_target:
      [
      false, # others
      false, # buildling
      false, # wall
      false, # obstacle
      false, # traffic_light
      false, # traffic_sign
      false, # person
      false, # vehicle
      false, # bike
      true, # road
      false, # sidewalk
      false, # roadPaint
      false, # curbstone
      false, # crosswalk
      true, # vegetation
      false, # sky
      ]
    # the maximum distance of pointcloud to be applied filter,
    # this is selected based on semantic segmentation model accuracy,
    # calibration accuracy and unknown reaction distance
    filter_distance_threshold: 60.0
