units:
  - name: /autoware/localization
  - name: /autoware/planning
  - name: /autoware/planning/route

  - name: /autoware/percepiton/front-obstable-detection
    type: any
    list:
      - [/sensing/lidars/front]
      - [/sensing/radars/front]

  - name: /autoware/perception/front-obstable-prediction
    type: all
    list:
      - [/sensing/lidars/front]
      - [/sensing/radars/front]
