files:
  - { package: system_diagnostic_graph, path: config/sample_diagnostic_graph2.yaml }

nodes:
  - name: /autoware/report
    type: and
    inputs:
      - { type: unit, name: /autoware/operation/stop }
      - { type: unit, name: /autoware/operation/autonomous }
      - { type: unit, name: /autoware/operation/local }
      - { type: unit, name: /autoware/operation/remote }
      - { type: unit, name: /autoware/operation/emergency-stop }
      - { type: unit, name: /autoware/operation/comfortable-stop }

  - name: /autoware/operation/stop
    type: dummy

  - name: /autoware/operation/autonomous
    type: and
    inputs:
      - { type: unit, name: /autoware/localization }
      - { type: unit, name: /autoware/planning }
      - { type: unit, name: /autoware/percepiton }

  - name: /autoware/operation/local
    type: dummy

  - name: /autoware/operation/remote
    type: and
    inputs:
      - { type: diag, hardware: test, name: /external/remote_command }

  - name: /autoware/operation/emergency-stop
    type: dummy

  - name: /autoware/operation/comfortable-stop
    type: and
    inputs:
      - { type: unit, name: /autoware/localization }
      - { type: unit, name: /autoware/planning }
      - { type: unit, name: /autoware/percepiton/front-obstable-detection }
