units:
  - name: /autoware/localization
    type: and
    list:
      - { type: diag, name: /sensing/lidars/top }

  - name: /autoware/planning
    type: and
    list:
      - { type: unit, name: /autoware/planning/route }

  - name: /autoware/planning/route
    type: and
    list:
      - { type: diag, name: /planning/route }

  - name: /autoware/percepiton
    type: and
    list:
      - { type: unit, name: /autoware/percepiton/front-obstable-detection }
      - { type: unit, name: /autoware/perception/front-obstable-prediction }

  - name: /autoware/percepiton/front-obstable-detection
    type: or
    list:
      - { type: diag, name: /sensing/lidars/front }
      - { type: diag, name: /sensing/radars/front }

  - name: /autoware/perception/front-obstable-prediction
    type: and
    list:
      - { type: diag, name: /sensing/lidars/front }
