files:
  - { package: system_diagnostic_graph, path: config/sample_diagnostic_graph2.yaml }

units:
  - name: /autoware/report
    type: all
    list:
      - { type: unit, name: /autoware/operation/stop }
      - { type: unit, name: /autoware/operation/autonomous }
      - { type: unit, name: /autoware/operation/local }
      - { type: unit, name: /autoware/operation/remote }
      - { type: unit, name: /autoware/operation/emergency-stop }
      - { type: unit, name: /autoware/operation/comfortable-stop }

  - name: /autoware/operation/stop
    type: ok

  - name: /autoware/operation/autonomous
    type: all
    list:
      - { type: unit, name: /autoware/localization }
      - { type: unit, name: /autoware/planning }
      - { type: unit, name: /autoware/percepiton }

  - name: /autoware/operation/local
    type: ok

  - name: /autoware/operation/remote
    type: all
    list:
      - { type: diag, name: /external/remote_command }

  - name: /autoware/operation/emergency-stop
    type: ok

  - name: /autoware/operation/comfortable-stop
    type: all
    list:
      - { type: unit, name: /autoware/localization }
      - { type: unit, name: /autoware/planning }
      - { type: unit, name: /autoware/percepiton/front-obstable-detection }
