/**:
  ros__parameters:
    update_rate: 10.0
    processing_time_topic_name_list:
      - /planning/scenario_planning/lane_driving/motion_planning/elastic_band_smoother/debug/processing_time_ms
      - /planning/scenario_planning/lane_driving/motion_planning/elastic_band_smoother/debug/processing_time_ms
      - /planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/debug/dynamic_obstacle_stop/processing_time_ms
