/**:
  ros__parameters:
    preprocessing:
      max_length: 50.0  # [m] maximum path length used for drivable area expansion
      downsample_factor: 1  # factor by which to downsample the input path for faster calculation

    expansion:
      extra_footprint_offset: 0.5  # [m] extra distance to add around the ego footprint
      max_expansion_distance: 0.0  # [m] maximum distance by which the drivable area can be expended
      avoid_dynamic_objects: true  # if true, the drivable area is not expanded in the predicted path of dynamic objects
      avoid_linestring_types:  # linestring types in the lanelet maps that will not be crossed when expanding the drivable area
        - guard_rail
        - road_border
