/**:
  ros__parameters:
    event_diag_list:
      vehicle_is_out_of_lane: ": lane_departure"
      trajectory_deviation_is_high: ": trajectory_deviation"
      localization_matching_score_is_low: ": scan_matching_status"
      localization_accuracy_is_low: ": localization_error_ellipse"
      map_version_is_different: ": map_version"
      trajectory_is_invalid: ": trajectory_point_validation"
      cpu_temperature_is_high: ": CPU Temperature"
      cpu_usage_is_high: ": CPU Usage"
      cpu_is_in_thermal_throttling: ": CPU Thermal Throttling"
      storage_temperature_is_high: ": HDD Temperature"
      storage_usage_is_high: ": HDD Usage"
      network_usage_is_high: ": Network Usage"
      clock_error_is_large: ": NTP Offset"
      gpu_temperature_is_high: ": GPU Temperature"
      gpu_usage_is_high: ": GPU Usage"
      gpu_memory_usage_is_high: ": GPU Memory Usage"
      gpu_is_in_thermal_throttling: ": GPU Thermal Throttling"
      driving_recorder_storage_error: ": driving_recorder"
      debug_data_logger_storage_error: ": bagpacker"
      emergency_stop_operation: ": emergency_stop_operation"
      vehicle_error_occurred: ": vehicle_errors"
      vehicle_ecu_connection_is_lost: ": can_bus_connection"
      obstacle_crash_sensor_is_activated: ": obstacle_crash"
      /control/command_gate/node_alive_monitoring: "vehicle_cmd_gate: heartbeat"
      /control/autonomous_driving/node_alive_monitoring: ": control_topic_status"
      /control/external_command_selector/node_alive_monitoring: "external_cmd_selector: heartbeat"
      /localization/node_alive_monitoring: ": localization_topic_status"
      /map/node_alive_monitoring: ": map_topic_status"
      /planning/node_alive_monitoring: ": planning_topic_status"
      /sensing/lidar/node_alive_monitoring: ": lidar_topic_status"
      /sensing/imu/node_alive_monitoring: ": imu_connection"
      /sensing/gnss/node_alive_monitoring: ": gnss_connection"
      /system/node_alive_monitoring: ": system_topic_status"
      /vehicle/node_alive_monitoring: ": vehicle_topic_status"
