# This file is automatically synced from:
# https://github.com/autowarefoundation/sync-file-templates
# To make changes, update the source repository and follow the guidelines in its README.

name: comment-on-pr
on:
  pull_request_target:

jobs:
  comment-on-pr:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Initial PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            Thank you for contributing to the Autoware project!

            🚧 If your pull request is in progress, [switch it to draft mode](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request#converting-a-pull-request-to-a-draft).

            Please ensure:
            - You've checked our [contribution guidelines](https://autowarefoundation.github.io/autoware-documentation/main/contributing/).
            - Your PR follows our [pull request guidelines](https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/).
            - All required CI checks pass before [marking the PR ready for review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request#marking-a-pull-request-as-ready-for-review).
