name: Comment on PR
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  comment-on-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Initial PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            Thank you for contributing to the Autoware project!

            🚧 If your pull request is in progress, switch it to draft mode.

            Please ensure:
            - You've checked our [contribution guidelines](https://autowarefoundation.github.io/autoware-documentation/main/contributing/).
            - Your PR follows our [pull request guidelines](https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/).
            - All required CI checks pass before marking the PR ready for review.
