name: cppcheck-differential

on:
  pull_request:

jobs:
  cppcheck-differential:
    runs-on: ubuntu-latest

    steps:
      - name: Set PR fetch depth
        run: echo "PR_FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> "${GITHUB_ENV}"

      - name: Checkout PR branch and all PR commits
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: ${{ env.PR_FETCH_DEPTH }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git

      # cppcheck from apt does not yet support --check-level args, and thus install from snap
      - name: Install Cppcheck from snap
        run: |
          sudo snap install cppcheck

      - name: Fetch the base branch with enough history for a common merge-base commit
        run: git fetch origin ${{ github.base_ref }}
        shell: bash

      - name: Get modified packages
        id: get-modified-packages
        uses: autowarefoundation/autoware-github-actions/get-modified-packages@v1

      - name: Run Cppcheck on changed packages
        if: ${{ steps.get-modified-packages.outputs.modified-packages != '' }}
        continue-on-error: true
        id: cppcheck
        run: |
          echo "Running Cppcheck on changed packages: ${{ steps.get-changed-packages.outputs.changed-packages }}"
          cppcheck --enable=all --inconclusive --check-level=exhaustive --error-exitcode=1 --suppressions-list=.cppcheck_suppressions --inline-suppr ${{ steps.get-changed-packages.outputs.changed-packages }} 2> cppcheck-report.txt
        shell: bash

      - name: Show cppcheck-report result
        if: ${{ steps.get-modified-packages.outputs.modified-packages != '' }}
        run: |
          cat cppcheck-report.txt

      - name: Upload Cppcheck report
        if: ${{ steps.get-modified-packages.outputs.modified-packages != '' }}
        uses: actions/upload-artifact@v2
        with:
          name: cppcheck-report
          path: cppcheck-report.txt

      - name: Fail the job if Cppcheck failed
        if: ${{ steps.get-modified-packages.outputs.modified-packages != '' && steps.cppcheck.outcome == 'failure' }}
        run: exit 1
