name: delete-closed-pr-docs

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  pre_condition:
    name: Don't run scheduled jobs on forks
    runs-on: ubuntu-latest
    if: ${{ (github.event_name != 'schedule') || (github.event_name == 'schedule' && github.repository == 'autowarefoundation/autoware.universe') }}
    steps:
      - run: "true"

  delete-closed-pr-docs:
    needs: pre_condition
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Delete closed PR docs
        uses: autowarefoundation/autoware-github-actions/delete-closed-pr-docs@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
