# This file is automatically synced from:
# https://github.com/autowarefoundation/sync-file-templates
# To make changes, update the source repository and follow the guidelines in its README.

name: delete-closed-pr-docs

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  delete-closed-pr-docs:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Delete closed PR docs
        uses: autowarefoundation/autoware-github-actions/delete-closed-pr-docs@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
