name: remove-old-pr-docs

on:
  pull_request_target:
    types:
      - closed

jobs:
  get-docs-version-name:
    uses: autowarefoundation/autoware-github-actions/.github/workflows/reusable-get-docs-version-name.yaml@6a086d5eac5effbed9876049233213f5cd358914

  remove-old-pr-docs:
    uses: autowarefoundation/autoware-github-actions/.github/workflows/reusable-remove-docs.yaml@6a086d5eac5effbed9876049233213f5cd358914
    needs: get-docs-version-name
    with:
      script-ref: 6a086d5eac5effbed9876049233213f5cd358914
      mkdocs-yaml: mkdocs.yaml
      version-name: ${{ needs.get-docs-version-name.outputs.version-name }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
