name: semantic-pull-request

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  semantic-pull-request:
    uses: autowarefoundation/autoware-github-actions/.github/workflows/reusable-semantic-pull-request.yaml@6a086d5eac5effbed9876049233213f5cd358914
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
