name: spell-check-pr

on:
  pull_request:

jobs:
  spell-check:
    uses: autowarefoundation/autoware-github-actions/.github/workflows/reusable-spell-check.yaml@6a086d5eac5effbed9876049233213f5cd358914
    with:
      cspell-json-url: https://raw.githubusercontent.com/tier4/autoware-spell-check-dict/main/cspell/.cspell.json
