/**:
  ros__parameters:
    lane_change:
      time_limit: 50.0 # [ms]
      backward_lane_length: 200.0
      backward_length_buffer_for_end_of_lane: 3.0 # [m]
      backward_length_buffer_for_blocking_object: 3.0 # [m]
      backward_length_from_intersection: 5.0 # [m]
      enable_stopped_vehicle_buffer: true

      # turn signal
      min_length_for_turn_signal_activation: 10.0 # [m]

      # terminal path
      terminal_path:
        enable: true
        disable_near_goal: true
        stop_at_boundary: false

      # trajectory generation
      trajectory:
        max_prepare_duration: 4.0
        min_prepare_duration: 2.0
        lateral_jerk: 0.5
        min_longitudinal_acc: -1.0
        max_longitudinal_acc: 1.0
        th_prepare_length_diff: 1.0
        th_lane_changing_length_diff: 1.0
        min_lane_changing_velocity: 2.78
        lon_acc_sampling_num: 5
        lat_acc_sampling_num: 3
        lane_changing_decel_factor: 0.5
        th_prepare_curvature: 0.03 # [/]

      # delay lane change
      delay_lane_change:
        enable: true
        check_only_parked_vehicle: false
        min_road_shoulder_width: 0.5  # [m]
        th_parked_vehicle_shift_ratio: 0.6

      # trajectory generation near terminal using frenet planner
      frenet:
        enable: true
        th_yaw_diff: 10.0  # [deg]
        th_curvature_smoothing: 0.1 # [/]

      # safety check
      safety_check:
        allow_loose_check_for_cancel: true
        enable_target_lane_bound_check: true
        stopped_object_velocity_threshold: 1.0 # [m/s]
        execution:
          expected_front_deceleration: -1.0
          expected_rear_deceleration: -1.0
          rear_vehicle_reaction_time: 2.0
          rear_vehicle_safety_time_margin: 1.0
          lateral_distance_max_threshold: 2.0
          longitudinal_distance_min_threshold: 3.0
          longitudinal_velocity_delta_time: 0.0
          extended_polygon_policy: "rectangle"
        parked:
          expected_front_deceleration: -1.0
          expected_rear_deceleration: -2.0
          rear_vehicle_reaction_time: 1.0
          rear_vehicle_safety_time_margin: 0.8
          lateral_distance_max_threshold: 1.0
          longitudinal_distance_min_threshold: 3.0
          longitudinal_velocity_delta_time: 0.0
          extended_polygon_policy: "rectangle"
        cancel:
          expected_front_deceleration: -1.0
          expected_rear_deceleration: -2.0
          rear_vehicle_reaction_time: 1.5
          rear_vehicle_safety_time_margin: 0.8
          lateral_distance_max_threshold: 1.0
          longitudinal_distance_min_threshold: 2.5
          longitudinal_velocity_delta_time: 0.0
          extended_polygon_policy: "rectangle"
        stuck:
          expected_front_deceleration: -1.0
          expected_rear_deceleration: -1.0
          rear_vehicle_reaction_time: 2.0
          rear_vehicle_safety_time_margin: 1.0
          lateral_distance_max_threshold: 2.0
          longitudinal_distance_min_threshold: 3.0
          longitudinal_velocity_delta_time: 0.0
          extended_polygon_policy: "rectangle"

        # lane expansion for object filtering
        lane_expansion:
          left_offset: 1.0 # [m]
          right_offset: 1.0 # [m]

      # lateral acceleration map
      lateral_acceleration:
        velocity: [0.0, 4.0, 10.0]
        min_values: [0.4,0.4,0.4]
        max_values: [0.65,0.65,0.65]

      # target object
      target_object:
        car: true
        truck: true
        bus: true
        trailer: true
        unknown: false
        bicycle: true
        motorcycle: true
        pedestrian: true

      # lane change regulations
      regulation:
        crosswalk: true
        intersection: true
        traffic_light: true

      # ego vehicle stuck detection
      stuck_detection:
        velocity: 0.5 # [m/s]
        stop_time: 3.0 # [s]

      # collision check
      collision_check:
        enable_for_prepare_phase:
          general_lanes: false
          intersection: true
          turns: true
        prediction_time_resolution: 0.5
        th_incoming_object_yaw: 2.3562 # [rad]
        yaw_diff_threshold: 3.1416 # [rad]
        check_current_lanes: false
        check_other_lanes: false
        use_all_predicted_paths: false

      # lane change cancel
      cancel:
        enable_on_prepare_phase: true
        enable_on_lane_changing_phase: true
        delta_time: 1.0                     # [s]
        duration: 5.0                       # [s]
        max_lateral_jerk: 100.0            # [m/s3]
        overhang_tolerance: 0.0             # [m]
        unsafe_hysteresis_threshold: 5     # [/]
        deceleration_sampling_num: 5 # [/]

      lane_change_finish_judge_buffer: 2.0      # [m]
      finish_judge_lateral_threshold: 0.1        # [m]
      finish_judge_lateral_angle_deviation: 1.0 # [deg]

      # debug
      publish_debug_marker: true
